[Debian] Enable -std=c++11
In Bionic, tf-lite build failed with:

In file included from /usr/include/c++/5/cstdint:35:0,
                 from tensorflow/lite/allocation.cc:22:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>